sudo: required
services:
    - docker

before_install:
    - docker build -t susishushi/react-test -f ./client/Dockerfile.dev ./client


script:
    - docker run -e CI=true susishushi/react-test npm test

after_success:
    - docker build -t sushishushi/multi-client ./client
    - docker build -t sushishushi/multi-nginx ./nginx
    - docker build -t sushishushi/multi-server ./server
    - docker build -t sushishushi/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to Docker hub 
    - docker push susishushi/multi-client
    - docker push susishushi/multi-nginx
    - docker push susishushi/multi-server
    - docker push susishushi/multi-worker