sudo: required
services:
    - docker

before_install:
    - docker build -t susishushi/react-test -f ./client/Dockerfile.dev ./client


script:
    - docker run -e CI=true susishushi/react-test npm test

after_success:
    - docker build -t nambaikin/multi-client ./client
    - docker build -t nambaikin/multi-nginx ./nginx
    - docker build -t nambaikin/multi-server ./server
    - docker build -t nambaikin/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to Docker hub 
    - docker push nambaikin/multi-client
    - docker push nambaikin/multi-nginx
    - docker push nambaikin/multi-server
    - docker push nambaikin/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-829887344435
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY